### ISSUE TITLE
PHPCI 1.7.1 do not support PHP 5.4 or 5.3

### ISSUE THREAD

**Issue by agarzon** [dancryer/PHPCI#1259]
Error when execute  **./console phpci:run-builds -vvv**

```
[2016-09-14 12:02:08] RunCommand.ALERT: Fatal Error (E_PARSE): syntax error, unexpected '{' {"code":4,"message":"syntax error, unexpected '{'","file":"/var/www/html/phpci/PHPCI/PHPCI/Builder.php","line":237} []
```

That line is:

```
        } finally {
            // Complete stage plugins are always run
            $this->pluginExecutor->executePlugins($this->config, 'complete');
        }
```

That line uses **finally**  on the exception, but **finally** was introduced in PHP5.5 http://php.net/manual/en/language.exceptions.php#language.exceptions.finally

So, there is no way builder will work with PHP5.3 and PHP5.4

**Comment by agarzon** [comment]
Btw, I commented that lines, and my builds are working as expected again. :+1:

**Comment by REBELinBLUE** [comment]
You do know PHP 5.5 has been end-of-life for a few months now? Yet alone the 1+ year that 5.4 has and 2+ that 5.3; it really is not advisable to use such outdated releases

**Comment by agarzon** [comment]
Of course. 

But PHPCI claims to support starting from PHP 5.3 
https://www.phptesting.org/wiki/Installing-PHPCI

**Comment by REBELinBLUE** [comment]
@dancryer you really should fix that

**Comment by Shade634** [comment]
Depends how you look at it, if older versions before (1.7.1) support PHP 5.3 ...
