### ISSUE TITLE
Is this repository is in active development state?

### ISSUE THREAD

**Issue by lakshmajim** [dancryer/PHPCI#1348]
Is this repository is in active development state .Just curious, as I need to look for alternative iff it was deprecated.

**Comment by aminebenhariz** [comment]
Same question here.
If the lead maintainer is no longer available or too busy, he should assign few maintainers to keep the project active.
Maybe we need to fork.

**Comment by ptejada** [comment]
See https://github.com/php-censor/php-censor

**Comment by aminebenhariz** [comment]
@ptejada Thank you!

**Comment by dancryer** [comment]
@lakshmajim @aminebenhariz Definitely looking for maintainers! PHPCI is not dead, the latest release is in a functional state and I'm attempting to do some tidy-up... but we need help to keep it going.

Feel free to email me `dan@phptesting.org` if you're keen.
