### ISSUE TITLE
Move external dependencies to local location

### ISSUE THREAD

**Issue by tvbeek** [dancryer/PHPCI#814]
I'm running PHPCI localy in combination with a local gitlab instance. This morning we had a problem in our internet connection. That isn't a problem because we have everything in house. But the loading of PHPCI was a problem because it use files from cloudflare.com, fonts.gstatic.com and google.com
Is it an idea to place them in PHPCI itself?

**Comment by mavimo** [comment]
:+1: 
Use bower to manage external JS dependency + RequireJS to load it from CDN OR if it fail from local.

**Comment by dancryer** [comment]
This would be a :-1: from me, but I am open to being convinced.

I almost always lean towards using cdnjs, as I don't think anyone does a good job of keeping external libraries like this up to date on a regular basis.

With that being said, we need to rework the front-end JS anyway (and reconsider how the build UI in particular is implemented.) So perhaps there's an opportunity to fix this that way?

**Comment by mavimo** [comment]
@dancryer For some client (where are actually not using PHPCI) we have all machine in a closed network that can't access to internet (I know is a rare uses case) but using external dependency loaded by CDN make impossible to use it.

I agree that the frontend part need more love and consider this in the structure refactoring can be good.

**Comment by tvbeek** [comment]
I personal don't like the use of cdns because if a cdn is down a lot of websites aren't working.
The idea from @mavimo to use a tool like bower to manage them is a good idea

**Comment by mikedamoiseau** [comment]
+1, sometimes the internet is very slow at the office, would be nice to have no assets on CDN.
Moreover, people using PHPCI are mostly professionals and in my opinion they should be able to manage their install themselves .
