### ISSUE TITLE
Create a statistics call on install or update

### ISSUE THREAD

**Issue by tvbeek** [dancryer/PHPCI#853]
I think it should be nice that during a installation or update of phpci the server will do a call to a central place to get statistics about the platform it runs on.
This data can be used to make decisions

Data I think about is:
- PHP version
- OS
- Install or update (and the old version if it is an update)
- ...

It should be optional to don't send the statistics

**Comment by dancryer** [comment]
I've wanted to do this for a long time. Been nervous that people would freak out about it...

**Comment by jfi** [comment]
Couldn't we always provide an opt-out option in a setting?

**Comment by tvbeek** [comment]
@dancryer I think that it isn't a big problem if we make it clear for anybody and only do it on update or install. Not every * period.

@jfi I think that is important to do

**Comment by dancryer** [comment]
We'd need to make it a question in the installer... Otherwise we'd have to send the stats at some later stage.

I'd like to do this though, I think it would be super valuable.
