### ISSUE TITLE
Reset the path to the buildpath and remove the getcwd commands from the plugins

### ISSUE THREAD

**Issue by tvbeek** [dancryer/PHPCI#881]
We have some getcwd calls to save and reset the path. But this give problems in some situations ( http://php.net/getcwd )
If we remove the getcwd and reset the path before every plugin we can fix this.
See https://github.com/Block8/PHPCI/search?utf8=%E2%9C%93&q=getcwd for the locations of getcwd

**Comment by dancryer** [comment]
I guess this would be resolved as part of #884 and #885?

**Comment by Adirelle** [comment]
It have given a look about this, by adding a "workingDirectory" attribute (and its accessors) to the CommandExecutor. Unfortunately, the PluginExecutor isn't aware of the CommandExecutor to reset the workdingDirectory between each plugin. 

Telling trhe PluginExecutor about the CommandExecutor would do the trick, but it would also add an undesirable dependency between the two components. A solution would to have some kind of callback in the PluginExecutor before executing each plugin. Any though about this, @dancryer ?
